services:
  my-server:
    build:
      context: .
      dockerfile: MyServerImageFile
    container_name: api-server-for-kiki-localhost-build
    ports:
      - 8080:8080
    depends_on:
      my-mysql:
        condition: service_healthy
      my-redis:
        condition: service_healthy

  my-mysql:
    image: mysql:8.0
    container_name: mysql-for-kiki-localhost-build
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: kiki_localhost
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      retries: 10

  my-redis:
    image: redis:7
    container_name: redis-for-kiki-localhost-build
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
      - ./redis-localhost.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10