services:
  my-mysql:
    image: mysql:8.0
    container_name: mysql-for-kiki-virtual-machine
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: kiki_testcase
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  my-redis:
    image: redis:7
    container_name: redis-for-kiki-virtual-machine
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
      - ./redis-localhost.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
