services:
  my-server:
    build: .
    container_name: kiki-api-server
    ports:
      - 8080:8080
    depends_on:
      my-mysql:
        condition: service_healthy
      my-redis:
        condition: service_healthy

  my-mysql:
    image: mysql
    container_name: mysql-for-kiki-localhost
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: kiki_localhost
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test:  ["CMD", "mysqladmin", "ping"]
      interval: 5s
      retries: 10

  my-redis:
    image: redis
    container_name: redis-for-kiki-localhost
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
      - ./redis-localhost.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10