# 로컬 개발용 도커 환경
# 실제 배포 환경이랑 db 비밀번호가 달라서 깃헙에 올라가도 OK

services:
  my-mysql:
    image: mysql
    container_name: mysql-for-kiki-localhost
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  my-redis:
    image: redis
    container_name: redis-for-kiki-localhost
    ports:
      - 6379:6379
