spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kiki_localhost
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    fail-on-missing-locations: true
    locations: classpath:db/migration
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: 0662d30d5260576c5b9a63b6508f7ae9
            client-secret: mFLFViBZS9mrY9MBY5RkSduypDkA4zwl
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image

logging:
  level:
    org:
      springframework:
        security: DEBUG

security:
  use-debug-mode: true
  jwt:
    secret-key: local-secret-keyyyyyyyyyyyyyyyyyy
  aes:
    secret-key: local-secret-key
    iv-secret-key: local-secret-key

cors:
  # 네이티브 앱이라 따로 도메인이 없고 쿠키도 사용 안 해서 *
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"