spring:
  datasource:
    url: jdbc:mysql://my-mysql:3306/kiki_localhost
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: my-redis
      port: 6379
      password: 123456

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  flyway:
    baseline-on-migrate: true
    fail-on-missing-locations: true
    locations: classpath:db/migration

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: 0662d30d5260576c5b9a63b6508f7ae9
            client-secret: mFLFViBZS9mrY9MBY5RkSduypDkA4zwl
            client-authentication-method: client_secret_post
            redirect-uri: https://swift-willing-panda.ngrok-free.app/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image

logging:
  level:
    org:
      springframework:
        security: DEBUG

security:
  use-debug-mode: true
  jwt:
    secure-algorithm: HmacSHA256
    secret-key: local-secret-keyyyyyyyyyyyyyyyyyy
  aes:
    secret-key: local-secret-key
    iv-secret-key: local-secret-key
    cipher-algorithm: AES/CBC/PKCS5Padding

server-base-url: https://swift-willing-panda.ngrok-free.app
kakaopay-redirect-base-url: https://qr.kakaopay.com
client:
  android:
    package-name: corp.pjh.kiki
    sha256-from-my-key: B4:DB:18:FC:5A:1A:47:7D:24:99:F4:8C:64:3A:35:13:B3:E4:25:26:51:40:63:AF:29:81:FE:3C:A6:F8:44:6E