name: EC2 배포

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v4

      - name: 레포지토리에 application.yml 업로드
        run: |
          # 기존 application-local.yml 파일은 이제 필요 없으니 삭제
          rm ./src/main/resources/application-local.yml
          
          # 원래 로컬에서 개발할 때는 local 프로필을 사용했었는데, 배포 환경이니 prod 프로필로 교체
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_PROD_YML }}" > ./src/main/resources/application-prod.yml

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: 개발 환경이랑 똑같이 도커 세팅 (MySQL & Redis)
        run: |
          # 미리 설정한 가상 머신 전용 컴포즈 파일 up
          docker compose -f ./compose-virtual-machine.yml up -d
          
          # 빌드 전 헬스 체크
          until docker exec mysql-for-kiki-virtual-machine mysqladmin -u root -p"123456" ping -h "127.0.0.1" && \
                docker exec redis-for-kiki-virtual-machine redis-cli -a "123456" ping | grep -q "PONG"; do
            echo "Waiting for MySQL and Redis to be ready..."
            sleep 2
          done

      - name: 테스트 및 빌드
        run: ./gradlew clean build

      - name: 테스트 및 빌드 실패 시 관련 리포트 업로드
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: ./build/reports/tests/test

      - name: AWS 유저 인증
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_USER_SECRET_KEY }}

      - name: ECR에 로그인
        uses: aws-actions/amazon-ecr-login@v2

      - name: 서버 이미지 빌드, ECR에 푸시
        run: |
          REPO_URL=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com
          
          docker build -t $REPO_URL/kiki-api-server:latest .
          
          docker push $REPO_URL/kiki-api-server:latest

      - name: 가상 머신 IP 조회
        id: ip
        uses: haythem/public-ip@v1.2

      - name: SSH 접속을 위한 가상 머신 IP 인바운드 규칙에 추가
        run: aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_EC2_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: 레포지토리에 compose-prod.yml, redis-prod.conf 업로드
        run: |          
          echo "${{ secrets.COMPOSE_PROD_YML }}" > ./compose-prod.yml
          echo "${{ secrets.REDIS_PROD_CONF }}" > ./redis-prod.conf

      - name: compose.yml 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ./compose-prod.yml
          target: /home/ubuntu/compose/compose-prod.yml

      - name: redis.conf 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ./redis-prod.conf
          target: /home/ubuntu/redis/config/redis-prod.conf

      - name: EC2 접속
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            REPO_URL=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com
            docker pull $REPO_URL/kiki-api-server:latest
            
#            docker compose -f /home/ubuntu/compose/compose-prod.yml down
#            # 모든 컨테이너가 종료될 때까지 대기
#            while [ "$(docker ps -q)" ]; do
#            sleep 2
#            done
#
#            docker compose -f /home/ubuntu/compose/compose-prod.yml up -d