name: EC2 배포

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 설치하기
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: 도커 세팅 및 서비스 헬스 체크 (MySQL & Redis)
        run: |
          docker compose -f compose-virtual-machine.yml up -d
          
          until docker exec mysql-for-kiki-virtual-machine mysqladmin -u root -p"123456" ping -h "127.0.0.1" --silent && \
                docker exec redis-for-kiki-virtual-machine redis-cli ping | grep -q "PONG"; do
            echo "Waiting for MySQL and Redis to be ready..."
            sleep 2
          done

      - name: application.yml 설정하기
        run: |
          rm src/main/resources/application-local.yml

          echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_PROD_YML }}" > src/main/resources/application-prod.yml

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar
